// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARsveyf0mFv0TVYybGQ4dYUeKIO18eV64',
    appId: '1:1077334253184:web:39a82b817038bb8dec1065',
    messagingSenderId: '1077334253184',
    projectId: 'alu-connect-3cf96',
    authDomain: 'alu-connect-3cf96.firebaseapp.com',
    storageBucket: 'alu-connect-3cf96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYx2Jf7MXDMYr3mKKyNa-PWi1HY37l5Kw',
    appId: '1:1077334253184:android:7e18113a0b55d9bcec1065',
    messagingSenderId: '1077334253184',
    projectId: 'alu-connect-3cf96',
    storageBucket: 'alu-connect-3cf96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb7Sq-sC1OHET0HTDdEMAedGtPiEuCSOg',
    appId: '1:1077334253184:ios:e04aa51032f9914fec1065',
    messagingSenderId: '1077334253184',
    projectId: 'alu-connect-3cf96',
    storageBucket: 'alu-connect-3cf96.firebasestorage.app',
    iosBundleId: 'com.example.aluconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb7Sq-sC1OHET0HTDdEMAedGtPiEuCSOg',
    appId: '1:1077334253184:ios:e04aa51032f9914fec1065',
    messagingSenderId: '1077334253184',
    projectId: 'alu-connect-3cf96',
    storageBucket: 'alu-connect-3cf96.firebasestorage.app',
    iosBundleId: 'com.example.aluconnect',
  );
}
